spring:
  application:
    name: welding_web
  profiles:
    active: dev


  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb


logging:
  config: classpath:config/logback-spring.xml


