server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - application/json
      - image/jpeg

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 6
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

logging:
  path: D:\springBootLog\welding\



